<a href="https://colab.research.google.com/github/ghanshyamverma4654/Mission-Data-Science/blob/master-branch/basiccs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
l = [1,2,3,4.5,"Hello"]
arr = np.array([l])
arr

array([['1', '2', '3', '4.5', 'Hello']], dtype='<U32')

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1 = np.arange(1,21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
matrix = arr1.reshape(4,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
np.random.randint(10,50,10)

array([42, 34, 42, 24, 42, 23, 19, 47, 42, 48])

In [ ]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr2.shape

(3, 4)

In [ ]:
arr2.size

12

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
v = arr2.min()
v

np.int64(1)

In [ ]:
arr2.max()

np.int64(12)

In [ ]:
arr2.sum()

np.int64(78)

In [ ]:
arr2.mean()

np.float64(6.5)

In [ ]:
c_sum = np.sum(arr2,axis=0)
c_sum

array([15, 18, 21, 24])

In [ ]:
r_sum = np.sum(arr2,axis=1)
r_sum

array([10, 26, 42])

In [ ]:
arr2.argmax()

np.int64(11)

In [ ]:
arr2.argmin()

np.int64(0)

In [ ]:
arr3 = np.arange(10,31)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [ ]:
arr3.reshape(7,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [ ]:
#Numpy Indexing

In [3]:
arr4 = np.arange(11,21)
arr4

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
#Indexing
arr4[-1] = 100
arr4

array([ 11,  12,  13,  14,  15,  16,  17,  18,  19, 100])

In [14]:
#Slicing
arr4[3:7]

array([14, 15, 16, 17])

In [15]:
arr4[3:]

array([ 14,  15,  16,  17,  18,  19, 100])

In [16]:
arr4[:5]

array([11, 12, 13, 14, 15])

In [18]:
arr4[:]

array([ 11,  12,  13,  14,  15,  16,  17,  18,  19, 100])

In [20]:
arr4[3::2]

array([ 14,  16,  18, 100])

In [19]:
A=arr4[-1::-1]
A

array([100,  19,  18,  17,  16,  15,  14,  13,  12,  11])

In [24]:
#Indexing and Slicing in Matrices
arr5 = np.arange(1,10).reshape(3,3)
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
#indexing
arr5[1]

array([4, 5, 6])

In [26]:
arr5[1,2]

np.int64(6)

In [27]:
arr5[0,0]


np.int64(1)

In [32]:
#slicing
arr5[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [33]:
arr5[:,2]

array([3, 6, 9])

In [34]:
#Boolean Indexing
arr6 = np.arange(11,21)
arr6

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
bool_index = arr6 % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [37]:
A1 = arr6[bool_index]
A1

array([12, 14, 16, 18, 20])

In [38]:
#Array Operations

In [39]:
#Arithmetic Operations
#Size of both arrays must be same to perform any arithmetic ops.
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [40]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [41]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [42]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [43]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [44]:
a1 // a2

array([0, 0, 0, 0, 0])

In [45]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [47]:
#Broadcasting
list1 = [10,20,30,40]
#list1 + 10
# TypeError: can only concatenate list (not "int") to list

In [48]:
arr7 = np.array(list1)
arr7

array([10, 20, 30, 40])

In [49]:
arr7 + 10
#No error

array([20, 30, 40, 50])

In [52]:
#Same can be done with Matrices too

A1 = arr7.reshape(2,2)
A1

array([[10, 20],
       [30, 40]])

In [54]:
A1 + 5

array([[15, 25],
       [35, 45]])

In [62]:
#Deep copy and Shallow copy
a = np.array([1,2,3,4,5])

In [60]:
#Deep Copy
b = a
b[3] = 8
b

array([1, 2, 3, 8, 5])

In [61]:
a
#Value has been changed via b

array([1, 2, 3, 8, 5])

In [65]:
#Shallow Copy
c = a.copy()
a

array([1, 2, 3, 4, 5])

In [66]:
c

array([1, 2, 3, 4, 5])

In [70]:
c[4] = 10

In [71]:
c

array([ 1,  2,  3,  4, 10])

In [72]:
a #Value at [4] will remain same in a

array([1, 2, 3, 4, 5])

In [87]:
#Matrix Operations
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[7,8],[9,10],[11,12]])

In [90]:
#Dot Product of X and Y
#For Dot Product Columns in X == Rows in Y
dot_product = np.dot(X,Y)
dot_product

array([[ 58,  64],
       [139, 154]])

In [91]:
#Transpose
X

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
T = X.T #Transpose = convert Rows of a Matrix into columns and vice-versa
T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [97]:
T.T

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
#Advance array Manipulation
#Stacking: Matrices can't be stacked but Vectors can.
#Stacking Arrays(Vectors)
x = np.array([1,2,3])
y = np.array([4,5,6])
#Size must be same of both arrays

In [105]:
np.vstack((x,y)) #Vertical Stack : Stacks arrays in up and down form

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
np.hstack((x,y)) #Horizontal Stack : Stacks arrays in a single line

array([1, 2, 3, 4, 5, 6])

In [107]:
#Column Stack : Stacks elements of each array into column
np.column_stack((x,y))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [111]:
#Splitting Arrays (Matrices)
z = np.arange(1,17).reshape(4,4)
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [112]:
#Horizontal Split
np.hsplit(z,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [115]:
#Vertical Split
np.vsplit(z,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]