<a href="https://colab.research.google.com/github/ghanshyamverma4654/Mission-Data-Science/blob/master-branch/exersises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Valid Sudoku**

In [ ]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
import numpy as np

In [ ]:
A = np.sum(s, axis=1)
for i in A:
  if i != 45:
    print("Not a valid sudoku")
    break
else:
  print("Valid sudoku for rows")

Valid sudoku


**General Questions**

In [ ]:
B = np.sum(s, axis=0)
for i in B:
  if i == 45:
    print("Valid sudoku for columns")
    break
else:
  print("Not a valid sudoku")

Valid sudoku for columns


In [38]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 75, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [30]:
#Find the average age of students.
ave_age = np.mean(data[0:6,0])
print(f"Average age of students : {ave_age}")

Average age of students : 18.4


In [ ]:
#Extract Math marks of all students.
Marks = data[0:6,1]
print(f"Maths marks of all students: {Marks}")

Maths marks of all students: [85 92 76 65 90]


In [31]:
#Find the highest Science mark.
highestScienceMark = np.max(data[0:6,2])
print(highestScienceMark)

95


In [32]:
#Get details of the student who scored more than 90 in Math.
N = data[0:6,1] > 90
print(data[N])

[[19 92 88]]


In [ ]:
#Increase Math marks of all students by 5.
print(f"Before : {data[0:6,1]}")
increased = data[0:6,1]+5
print(f"After: {increased}")


Before : [85 92 75 65 90]
After: [90 97 80 70 95]


In [ ]:
#Find how many students are younger than 19.
age = data[0:6,0]
#
count = 0
arr = []
for i in age:
  if i < 19:
    count += 1
    arr.append(i)
print(f"There are {count} students younger than 19 : {np.array(arr)}")

There are 3 students younger than 19 : [18 17 18]


In [33]:
#Calculate the average marks in each subject (column-wise mean).
averageInMaths = np.mean(data[0:6,1])
averageInScience = np.mean(data[0:6,2])
print(f"Average marks in Maths : {averageInMaths}\nAverage marks in Science : {averageInScience}")

Average marks in Maths : 81.4
Average marks in Science : 83.2


In [34]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [39]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 75, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [36]:
from os import CLD_CONTINUED
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 75, 95],
       [18, 65,  0],
       [20, 90, 85]])