<a href="https://colab.research.google.com/github/ghanshyamverma4654/Mission-Data-Science/blob/master-branch/Weekly_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
arr = np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
mat = np.arange(10,20).reshape(2,5)
mat

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
type(mat)

numpy.ndarray

In [ ]:
mat2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
mat2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
random = np.random.rand()
random

0.8664791709660277

In [ ]:
random2 = np.random.rand(5)
random2

array([0.06480463, 0.82775627, 0.99066103, 0.38896812, 0.59448824])

In [ ]:
random3 = np.random.rand(1,10)
random3

array([[0.17441043, 0.99955082, 0.60237322, 0.54417093, 0.18444576,
        0.17344021, 0.65719668, 0.92789212, 0.12004027, 0.43781114]])

In [ ]:
random4 = np.random.rand(1,10,5)
random4

array([[[0.83924049, 0.9850797 , 0.37402303, 0.38221118, 0.83792667],
        [0.07091512, 0.83519132, 0.01643105, 0.43756961, 0.41614014],
        [0.24149126, 0.69197362, 0.908849  , 0.32740054, 0.8816488 ],
        [0.0577626 , 0.70056486, 0.59022084, 0.26718098, 0.81077199],
        [0.81450609, 0.10931305, 0.73769797, 0.02529312, 0.98733403],
        [0.88823311, 0.69267489, 0.69456311, 0.69149506, 0.85035344],
        [0.93411629, 0.56343481, 0.31118102, 0.44935967, 0.15932878],
        [0.38315723, 0.79637304, 0.163652  , 0.60545588, 0.73115929],
        [0.74480407, 0.45502494, 0.70016455, 0.34364022, 0.40474911],
        [0.94910141, 0.93575248, 0.48041394, 0.56253205, 0.05959961]]])

In [ ]:
random5 = np.random.randn()
random5

-0.05579002441852411

In [ ]:
random51 = np.random.randn(100)
random51

array([-1.01168372,  0.23317483,  0.48375294, -0.88092782,  1.28812623,
        1.5464879 , -0.4755805 ,  0.31727338, -1.27828589, -1.08829435,
        0.55187489, -1.03782063, -0.25776014,  2.18253306, -1.23258837,
        0.02771615,  0.51831366,  0.64258515,  0.40525982, -0.16736456,
        0.11648254, -1.59994951,  0.78709958,  1.07148447,  0.67516768,
       -0.03266154, -0.29923484, -1.10591709,  0.31292032, -0.91112648,
        0.09549714,  1.42995526,  1.87652643, -2.08784052,  0.0683017 ,
        0.81058669, -0.45776755, -0.40002291,  0.85643517, -1.07688918,
        0.4318463 ,  1.52106921, -1.3099402 ,  1.54030636, -0.25026237,
        1.01764141, -1.03933691, -0.99836686, -0.31178989, -1.50475868,
        0.84794715,  0.34853807, -0.03171806,  2.32171542, -0.12829452,
       -0.97050886, -0.92850344,  0.12654462,  1.53539802,  1.47974629,
        0.89110568,  1.29392468, -0.12093484, -0.19206261, -0.73962579,
       -0.13702581,  0.31000675,  0.88543903, -1.02586391,  2.38

In [ ]:
random6 = np.random.randint(10)
random6

4

In [ ]:
random61 = np.random.randint(50,100)
random61

75

In [ ]:
random62 = np.random.randint(50,100,10)
random62

array([54, 52, 79, 96, 56, 76, 66, 92, 63, 75])

In [ ]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
ones1 = np.ones((5,5))
ones1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
zeros = np.zeros((10,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
lin = np.linspace(50,100,10)
lin

array([ 50.        ,  55.55555556,  61.11111111,  66.66666667,
        72.22222222,  77.77777778,  83.33333333,  88.88888889,
        94.44444444, 100.        ])

In [ ]:
lin.shape

(10,)

In [ ]:
zeros.shape

(10, 5)

In [ ]:
zeros.size

50

In [ ]:
zeros.ndim

2

In [ ]:
lin.ndim

1

In [ ]:
lin.dtype

dtype('float64')

In [ ]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
mat

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
mat2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr.min()

np.int64(10)

In [ ]:
mat.max()

np.int64(19)

In [ ]:
mat2.sum()

np.int64(78)

In [ ]:
np.sum(mat2,axis=1)

array([10, 26, 42])

In [ ]:
mat2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.sum(mat2,axis=0)

array([15, 18, 21, 24])

In [ ]:
mat2.mean()

np.float64(6.5)

In [ ]:
mat2.std()

np.float64(3.452052529534663)

In [ ]:
mat

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
mat.argmax()

np.int64(9)

In [ ]:
mat.argmin()

np.int64(0)

**Reshape**

In [ ]:
arr1 = np.arange(1,10)

In [ ]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2 = arr1.reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2 = arr2.reshape(-1)

In [ ]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
c = arr1.resize(3,3)
print(c)

None


In [ ]:
arr3 = np.array([1,2,3,4,5])
arr3

array([1, 2, 3, 4, 5])

In [ ]:
a = np.resize(arr3,(3,4))
a

array([[1, 2, 3, 4],
       [5, 1, 2, 3],
       [4, 5, 1, 2]])

In [ ]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mat

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
mat2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
mat2[2,2]

np.int64(11)

In [ ]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[10]

np.int64(20)

In [ ]:
#slicing
arr[:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[3:]

array([13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[:5]

array([10, 11, 12, 13, 14])

In [ ]:
arr[2:8]

array([12, 13, 14, 15, 16, 17])

In [ ]:
arr[::2]

array([10, 12, 14, 16, 18, 20])

In [ ]:
arr[:3:2]

array([10, 12])

In [ ]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[3::3]

array([13, 16, 19])

In [ ]:
#WHERE
np.where(arr == 15)

(array([5]),)

In [ ]:
np.where(arr > 15, 00, 100)
#If element is greater than 15 replace with 0, else replace with 100

array([100, 100, 100, 100, 100, 100,   0,   0,   0,   0,   0])

In [ ]:
#Indexing Matrix
mat2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
mat2[1,2]#7

np.int64(7)

In [ ]:
mat2[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [ ]:
#Broadcasting
mat3 = mat2 + 5
mat3

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [ ]:
#Copy
mat4 = mat3
mat4

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [ ]:
mat4 = mat4 + 2

In [ ]:
mat3

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [ ]:
mat4

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
mat5 = mat3.copy()

In [ ]:
mat5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [ ]:
mat5 = mat5 + 10

In [ ]:
mat5

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [ ]:
mat3

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [ ]:
a1 = np.array([[1,2],[3,4]])
b1 = np.arange(5,9).reshape(2,2)

In [ ]:
a1

array([[1, 2],
       [3, 4]])

In [ ]:
b1

array([[5, 6],
       [7, 8]])

In [ ]:
#Dot product
c1 = a1 @ b1
c1

array([[19, 22],
       [43, 50]])

In [ ]:
c2 = np.dot(a1,b1)
c2

array([[19, 22],
       [43, 50]])

In [ ]:
c2.T

array([[19, 43],
       [22, 50]])

In [ ]:
np.transpose(c2)

array([[19, 43],
       [22, 50]])